#!/usr/bin/env bash


#***********************************************#
#		  PiBadge 24			#
#		July 25th 2016			#
#						#
#          A LithoChasm / Toastyguy / 		#
#   Your Name Here if you contribute Production #
#						#
#   	    Defcon 24 / Bsides LV 8		#
#***********************************************#


## Check if being run as root
if [ "$(whoami)" != "root" ]; then
  echo "Error 404, root user not found"
  exit 1
fi


## Check if first run ##
FILE='/etc/badgeConfigured' 
if [ -f $FILE ]; then  		#if file exsists assume badge is configured
  echo -e "\033[0;32m Badge is green, supergreen \033[0m"
  exit 0
else
  echo -e "\033[1;31m Follow the white rabbit. Configuring Badge \033[0m"
fi


## Setup Keyboard ##
#cp locale.gen /etc/locale.gen
#/usr/sbin/locale-gen
#cp keyboard /etc/default/keyboard
#dpkg-reconfigure -f noninteractive keyboard-configuration

## Setup Network ##i
if cp interfaces /etc/network; then
    echo "* Network Config Succedded"
else
    echo "! Network Config Failled" 
fi

## Setup SSH
if [ $(systemctl is-active ssh) == "active" ]; then
  echo "* SSH is on"
else
  echo "* Enabling SSH"
  systemctl ssh enable
  systemctl ssh start
fi

## Install Software ##
#install omxplayer
dpkg -i fonts-freefont-ttf_20120503-4_all.deb
dpkg -i libpcre3_2%3a8.35-3.3+deb8u4_armhf.deb
dpkg -i libtevent0_0.9.25-0+deb8u1_armhf.deb
dpkg -i libntdb1_1.0-5_armhf.deb
dpkg -i libtdb1_1.3.6-0+deb8u1_armhf.deb
dpkg -i libldb1_2%3a1.1.20-0+deb8u1_armhf.deb
dpkg -i python-talloc_2.1.2-0+deb8u1_armhf.deb
dpkg -i samba-libs_2%3a4.2.10+dfsg-0+deb8u3_armhf.deb
dpkg -i libssh-4_0.6.3-4+deb8u2_armhf.deb
dpkg -i libsmbclient_2%3a4.2.10+dfsg-0+deb8u3_armhf.deb
dpkg -i omxplayer_0.3.7\~git20160713\~66f9076_armhf.deb

#install fbcp

#install other

## Setup video auto run at boot ##

## Disable this config script if all is good ##


exit 0  ## End cleanly
