#!/usr/bin/env bash


#***********************************************#
#		  PiBadge 24			#
#		July 25th 2016			#
#						#
#          A LithoChasm / Toastyguy / 		#
#   Your Name Here if you contribute Production #
#						#
#   	    Defcon 24 / Bsides LV 8		#
#***********************************************#


## Check if being run as root
if [ "$(whoami)" != "root" ]; then
  echo "Error 404, root user not found"
  exit 1
fi


## Check if first run ##
FILE='/etc/badgeConfigured' 
if [ -f $FILE ]; then  		#if file exsists assume badge is configured
  echo -e "\033[0;32m Badge is green, supergreen \033[0m"
  exit 0
else
  echo -e "\033[1;31m Follow the white rabbit. Configuring Badge \033[0m"
fi


## Setup Keyboard ##
cp locale.gen /etc/locale.gen
/usr/sbin/locale-gen
cp keyboard /etc/default/keyboard
dpkg-reconfigure -f noninteractive keyboard-configuration

## Setup Network ##
if cp interfaces /etc/network; then
    echo "* Network Config Succedded"
else
    echo "! Network Config Failled" 
fi

## Setup SSH
if [ $(systemctl is-active ssh) == "active" ]; then
  echo "* SSH is on"
else
  echo "* Enabling SSH"
  systemctl ssh enable
  systemctl ssh start
fi


## Setup console no blanking
echo " Disabling console blanking"
echo "consoleblank=0" >> /boot/cmdline.txt
i

## Setup Boot options
echo " Setting up boot options"
cp config.txt /boot/

## Setup auto run at boot ##
cp rc.local /etc/

## Resize Drive
echo " Resizing drive, will reboot when finished"
rm /etc/badgeConfigured
##resize

exit 0  ## End cleanly
