#!/usr/bin/env bash


#Sets the playlist to play:
$DEFAULT 
# $BSIDES
# $DEFCON

##Turns off cursor blink on display
setterm -console off > /dev/tty0

##Clear the term before firing up omxplayer
clear > /dev/tty0



if [ -v $DEFAULT ]
then
  echo "Default Playlist"
  ## Play some videos
  omxplayer --loop --fps 24 --no-osd -z --aspect-mode stretch /home/pi/PiBadge24/videos/default.mp4 &
  clear > /dev/tty0
  setterm -console on > /dev/tty0

else
  echo "Nothing"

fi

